// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "calculator.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



helloworld::Calculation_ptr helloworld::Calculation_Helper::_nil() {
  return ::helloworld::Calculation::_nil();
}

::CORBA::Boolean helloworld::Calculation_Helper::is_nil(::helloworld::Calculation_ptr p) {
  return ::CORBA::is_nil(p);

}

void helloworld::Calculation_Helper::release(::helloworld::Calculation_ptr p) {
  ::CORBA::release(p);
}

void helloworld::Calculation_Helper::marshalObjRef(::helloworld::Calculation_ptr obj, cdrStream& s) {
  ::helloworld::Calculation::_marshalObjRef(obj, s);
}

helloworld::Calculation_ptr helloworld::Calculation_Helper::unmarshalObjRef(cdrStream& s) {
  return ::helloworld::Calculation::_unmarshalObjRef(s);
}

void helloworld::Calculation_Helper::duplicate(::helloworld::Calculation_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

helloworld::Calculation_ptr
helloworld::Calculation::_duplicate(::helloworld::Calculation_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

helloworld::Calculation_ptr
helloworld::Calculation::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


helloworld::Calculation_ptr
helloworld::Calculation::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

helloworld::Calculation_ptr
helloworld::Calculation::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculation _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculation* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculation;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* helloworld::Calculation::_PD_repoId = "IDL:helloworld/Calculation:1.0";


helloworld::_objref_Calculation::~_objref_Calculation() {
  
}


helloworld::_objref_Calculation::_objref_Calculation(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::helloworld::Calculation::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
helloworld::_objref_Calculation::_ptrToObjRef(const char* id)
{
  if (id == ::helloworld::Calculation::_PD_repoId)
    return (::helloworld::Calculation_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::helloworld::Calculation::_PD_repoId))
    return (::helloworld::Calculation_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for helloworld::Calculation::calcSin

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cstring
class _0RL_cd_fc95a45d181aed7d_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_fc95a45d181aed7d_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  const int arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_fc95a45d181aed7d_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_fc95a45d181aed7d_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_fc95a45d181aed7d_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_fc95a45d181aed7d_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_fc95a45d181aed7d_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_fc95a45d181aed7d_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_fc95a45d181aed7d_00000000* tcd = (_0RL_cd_fc95a45d181aed7d_00000000*)cd;
  helloworld::_impl_Calculation* impl = (helloworld::_impl_Calculation*) svnt->_ptrToInterface(helloworld::Calculation::_PD_repoId);
  tcd->result = impl->Calculation(tcd->arg_0);


}

char* helloworld::_objref_Calculation::calcSin(const int nmax)
{
  _0RL_cd_fc95a45d181aed7d_00000000 _call_desc(_0RL_lcfn_fc95a45d181aed7d_10000000, "calcSin", 11);
  _call_desc.arg_0 = mesg;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

helloworld::_pof_Calculation::~_pof_Calculation() {}


omniObjRef*
helloworld::_pof_Calculation::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::helloworld::_objref_Calculation(ior, id);
}


::CORBA::Boolean
helloworld::_pof_Calculation::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::helloworld::Calculation::_PD_repoId))
    return 1;
  
  return 0;
}

const helloworld::_pof_Calculation _the_pof_helloworld_mCalculation;

helloworld::_impl_Calculation::~_impl_Calculation() {}


::CORBA::Boolean
helloworld::_impl_Calculation::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "calcSin")) {

    _0RL_cd_fc95a45d181aed7d_00000000 _call_desc(_0RL_lcfn_fc95a45d181aed7d_10000000, "calcSin", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
helloworld::_impl_Calculation::_ptrToInterface(const char* id)
{
  if (id == ::helloworld::Calculation::_PD_repoId)
    return (::helloworld::_impl_Calculation*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::helloworld::Calculation::_PD_repoId))
    return (::helloworld::_impl_Calculation*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
helloworld::_impl_Calculation::_mostDerivedRepoId()
{
  return ::helloworld::Calculation::_PD_repoId;
}

POA_helloworld::Calculation::~Calculation() {}

